language: objective-c
branches:
  only:
    - master
before_install:
    - gem install xcpretty
    - cd Tests && pod install && cd $TRAVIS_BUILD_DIR
before_script:
    - sudo easy_install cpp-coveralls
after_success:
    - ./coveralls.rb --extension m --exclude-folder Tests
script:
    - set -o pipefail
    - xcodebuild test -workspace Tests/YLMomentTests.xcworkspace -scheme 'iOSTests' -sdk iphonesimulator -configuration Release ONLY_ACTIVE_ARCH=NO | xcpretty -c
    - xcodebuild test -workspace Tests/YLMomentTests.xcworkspace -scheme 'OSXTests' -sdk macosx -configuration Release ONLY_ACTIVE_ARCH=NO | xcpretty -c
